const SUCCESS = 0, NOT_MATCHING_PAIR = 1, INVALID_CHAR = 2, NO_INPUT = 3;

exports.SUCCESS = SUCCESS;
exports.NOT_MATCHING_PAIR = NOT_MATCHING_PAIR;
exports.INVALID_CHAR = INVALID_CHAR;
exports.NO_INPUT = NO_INPUT;
